// rootlayout.tsx
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "@/components/partials/ConditionalHeader";
import ConditionalFooter from "@/components/partials/ConditionalFooter";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { SessionProviderWrapper } from "@/components/SessionProviderWrapper";
import dynamic from "next/dynamic";
// import SpinnerWrapper from "@/components/partials/SpinnerWrapper";
config.autoAddCss = false;

const montserrat = Montserrat({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Code Sprint",
  description: "Generated by create next app",
};

const SpinnerWrapper = dynamic(
  () => import("@/components/partials/SpinnerWrapper"),
  {
    ssr: false,
  }
);
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SessionProviderWrapper>
          <SpinnerWrapper>
            <ConditionalHeader />
            {children}
            <ConditionalFooter />
          </SpinnerWrapper>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
