name: CodeSprint_Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t nischalkshaj/codesprint -f ./Dockerfile.backend .

      - name: Build Frontend Docker Image
        run:
          docker build -t nischalkshaj/codesprint/frontend -f ./Dockerfile.frontend \
          --build-arg NEXT_APP_ENV='production' \
          --build-arg NEXT_PUBLIC_SERVER_URL='${{ secrets.NEXT_PUBLIC_SERVER_URL }}' .

      - name: Publish Backend Docker Image to Docker Hub
        run: docker push nischalkshaj/codesprint:latest

      - name: Publish Frontend Docker Image to Docker Hub
        run: docker push nischalkshaj/codesprint/frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Backend Docker Image from Docker Hub
        run: docker pull nischalkshaj/codesprint:latest

      - name: Pull Frontend Docker Image from Docker Hub
        run: docker pull nischalkshaj/codesprint/frontend:latest

      - name: Stop and Remove Existing Backend Container
        run: |
          if [ $(docker ps -q -f name=codesprint-app-container) ]; then
            docker stop codesprint-app-container
            docker rm codesprint-app-container
          fi

      - name: Stop and Remove Existing Frontend Container
        run: |
          if [ $(docker ps -q -f name=codesprint-frontend-container) ]; then
            docker stop codesprint-frontend-container
            docker rm codesprint-frontend-container
          fi

      - name: Run Backend Docker Container
        run: |
          docker run -d -p 4000:4000 \
          --name codesprint-app-container \
          -e NODE_ENV='production' \
          -e MONGODB_LOCAL_URI='mongodb://localhost:27017/code_sprint' \
          -e MONGODB_CLOUD_URI='${{ secrets.MONGODB_URI }}' \
          -e ACCESS_KEY='${{ secrets.ACCESS_KEY }}' \
          -e BUCKET_SECRET_KEY='${{ secrets.BUCKET_SECRET_KEY }}' \
          -e REGION='${{ secrets.REGION }}' \
          -e BUCKET_NAME='${{ secrets.BUCKET_NAME }}' \
          -e SQS_QUEUE_URL='${{ secrets.SQS_QUEUE_URL }}' \
          nischalkshaj/codesprint:latest

      - name: Run Frontend Docker Container
        run: |
          docker run -d -p 80:80 \
          --name codesprint-frontend-container \
          nischalkshaj/codesprint/frontend:latest

      - name: Check Backend Logs if Container Fails
        if: failure()
        run: docker logs codesprint-app-container

      - name: Check Frontend Logs if Container Fails
        if: failure()
        run: docker logs codesprint-frontend-container
