name: CodeSprint_Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/package-lock.json
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t nischalkshaj/codesprint/backend:latest -f ./Dockerfile.backend .

      - name: Build Frontend Docker Image
        run: docker build -t nischalkshaj/codesprint/frontend:latest -f ./Dockerfile.frontend --build-arg NEXT_APP_ENV='production' --build-arg NEXT_PUBLIC_SERVER_URL='${{ secrets.NEXT_PUBLIC_SERVER_URL }}' .

      - name: Publish Backend Docker Image to Docker Hub
        run: docker push nischalkshaj/codesprint/backend:latest

      - name: Publish Frontend Docker Image to Docker Hub
        run: docker push nischalkshaj/codesprint/frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Backend Docker Image from Docker Hub
        run: docker pull nischalkshaj/codesprint/backend:latest

      - name: Pull Frontend Docker Image from Docker Hub
        run: docker pull nischalkshaj/codesprint/frontend:latest

      - name: Verify Backend Docker Image
        run: docker images nischalkshaj/codesprint/backend:latest || exit 1

      - name: Verify Frontend Docker Image
        run: docker images nischalkshaj/codesprint/frontend:latest || exit 1

      - name: Stop and Remove Existing Backend Container
        run: |
          if [ $(docker ps -q -f name=codesprint-backend-container) ]; then
            docker stop codesprint-backend-container
            docker rm codesprint-backend-container
          fi

      - name: Run Backend Docker Container
        run: |
          docker run -d -p 4000:4000 \
          --name codesprint-backend-container \
          --restart unless-stopped \
          -e NODE_ENV='production' \
          -e MONGODB_LOCAL_URI='mongodb://localhost:27017/code_sprint' \
          -e MONGODB_CLOUD_URI='${{ secrets.MONGODB_URI }}' \
          -e ACCESS_KEY='${{ secrets.ACCESS_KEY }}' \
          -e BUCKET_SECRET_KEY='${{ secrets.BUCKET_SECRET_KEY }}' \
          -e REGION='${{ secrets.REGION }}' \
          -e BUCKET_NAME='${{ secrets.BUCKET_NAME }}' \
          -e SQS_QUEUE_URL='${{ secrets.SQS_QUEUE_URL }}' \
          nischalkshaj/codesprint/backend:latest

      - name: Stop and Remove Existing Frontend Container
        run: |
          if [ $(docker ps -q -f name=codesprint-frontend-container) ]; then
            docker stop codesprint-frontend-container
            docker rm codesprint-frontend-container
          fi

      - name: Run Frontend Docker Container
        run: |
          docker run -d -p 80:80 \
          --name codesprint-frontend-container \
          --restart unless-stopped \
          nischalkshaj/codesprint/frontend:latest

      - name: Check Logs if Backend Container Fails
        if: failure()
        run: docker logs codesprint-backend-container

      - name: Check Logs if Frontend Container Fails
        if: failure()
        run: docker logs codesprint-frontend-container

      - name: Clean Up Docker System
        run: docker system prune -f
