name: CodeSprint_Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t nischalkshaj/codesprint -f ./Dockerfile.backend .

      - name: Publish Docker Image to Docker Hub
        run: docker push nischalkshaj/codesprint:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Docker Hub
        run: docker pull nischalkshaj/codesprint:latest

      - name: Stop and Remove Existing Container
        run: |
          if [ $(docker ps -q -f name=codesprint-app-container) ]; then
            docker stop codesprint-app-container
            docker rm codesprint-app-container
          fi

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 \
          --name codesprint-app-container \
          -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
          -e AWS_ACCESS_KEY_ID='${{ secrets.ACCESS_KEY }}' \
          -e AWS_SECRET_ACCESS_KEY='${{ secrets.BUCKET_SECRET_KEY }}' \
          -e AWS_REGION='${{ secrets.REGION }}' \
          -e S3_BUCKET_NAME='${{ secrets.BUCKET_NAME }}' \
          -e SQS_QUEUE_URL='${{ secrets.SQS_QUEUE_URL }}' \
          nischalkshaj/codesprint:latest

      - name: Check Logs if Container Fails
        if: failure()
        run: docker logs codesprint-app-container
